# Generated by Django 4.0 on 2021-12-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.ImageField(null=True, upload_to='auction/'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='duration_type',
            field=models.CharField(choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long')], max_length=6),
        ),
    ]
